### ISSUE TITLE
修改之后 用哪个密钥连接啊   所有人都连不上了？

### ISSUE THREAD

**Issue by PureWaterSun** [EmYiQing/ShiroHacker#2]
为什么修改提示成功了 然后用明文的自定义的key去检测，密钥不正确  能不能帮忙解答一下  修改之后的密钥该怎么看啊

**Comment by EmYiQing** [comment]
KEY修改后就看不到了，只能用KEY加密新的SimplePrincipleCollection探测，无法查看。想要查看修改后的KEY只有一个办法，借助Java Agent之类的技术从JVM里面找，这样就太麻烦了

我当时测试了，修改成功后，密钥会变成你需要的，没有BUG。默认KEY是4ra1n_Big_HacKeR，如果你的KEY格式错误，应该也会使用这个KEY，因为KEY必须是16位的

**Comment by PureWaterSun** [comment]
这是来自QQ邮箱的自动回复邮件。
 已收到！

**Comment by EmYiQing** [comment]
另外，这个项目偏向于安全研究，而不是实战，所以可能有不完善的地方。如果你需要实战使用，我推荐SummerSec师傅的项目：https://github.com/SummerSec/ShiroAttack2
